# Generated by Django 4.1.5 on 2023-01-24 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='image',
            field=models.ImageField(max_length=200, upload_to=None),
        ),
    ]
