# Generated by Django 4.1.5 on 2023-01-25 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_drink_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='achievements',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='analytics',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='drink',
            new_name='drink_id',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='userlists',
            old_name='user',
            new_name='user_id',
        ),
    ]
