# Generated by Django 4.1.5 on 2023-01-23 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_achievements_analytics_comment_drink_user_userlists_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drink',
            name='user_lists',
        ),
    ]
